### PR TITLE
fix: Hydration error

### PR DESCRIPTION
**Pull request by web-97**
`Fix bug with hydration in development mode`

### CODE REVIEW

**Comment by Yidadaa** [comment]
请提供对应的报错截图。

**Comment by web-97** [comment]
git clone xxx
cd xxx
yarn
yarn run dev
WX20230522-150518
node -v:v16.19.1
npm-v:9.6.6

**Comment by Yidadaa** [comment]
请使用 nodejs18 及以上，nodejs16 即将迎来生命周期的结束。

**Comment by Yidadaa** [comment]
https://nodejs.org/en/blog/announcements/nodejs16-eol

**Comment by web-97** [comment]
我升级到了v18.16.0
删除了.next、node_modules并重新安装了依赖，这个错误依旧存在

**Comment by web-97** [comment]
在codesandbox上也有同样的问题https://codesandbox.io/p/github/web-97/ChatGPT-Next-Web/main?file=%2Fapp%2Fcomponents%2Fhome.tsx%3A85%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhyixcmn000a3b6kih4t5m1n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clhyixcmn000a3b6kih4t5m1n%2522%253A%257B%2522id%2522%253A%2522clhyixcmn000a3b6kih4t5m1n%2522%252C%2522activeTabId%2522%253A%2522clhyj2k2n003v3b6knufj0y1d%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clhyj2k2n003v3b6knufj0y1d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clhyj2w7f009o3b6k7wbqcdth%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522EMPTY_DEVTOOL%2522%252C%2522id%2522%253A%2522clhyj4b8a00u43b6k3x2z8ldc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fcomponents%252Fhome.tsx%2522%252C%2522id%2522%253A%2522clhyj50a600z73b6kd4s97bgq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Pull request closed without merging**
