### PR TITLE
translation to spanish strings with new.ts

### PR DESCRIPTION
**Pull request by johnfelipe**

### CODE REVIEW

**Comment by johnfelipe** [comment]
Anyone?

**Comment by johnfelipe** [comment]
Somethings wrong?

**Comment by johnfelipe** [comment]
I follow translate.md
Pls Review and tell me if I need follow more steps

**Comment by Yidadaa** [comment]
We already have Spanish:

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/locales/es.ts

**Pull request closed without merging**
