### PR TITLE
Update route.ts to deploy on cloudflare

### PR DESCRIPTION
**Pull request by PaperPlaneDeemo**
I deployed this application on Cloudflare and an error occured, it need to change into edge and can fix the error

### CODE REVIEW

**Comment by H0llyW00dzZ** [comment]
yeah this need edge instead of nodejs
also runtime edge can be used tauri app updater for client

**Comment by Yidadaa** [comment]
Vercel does not allow request forwarding at the edge runtime, which would break compatibility on the Vercel platform.

**Comment by PaperPlaneDeemo** [comment]
> Vercel does not allow request forwarding at the edge runtime, which would break compatibility on the Vercel platform.

i have depoyed on vercel with edge runtime and everything works well

**Comment by H0llyW00dzZ** [comment]
wait what, how that can break compatibility.

**Comment by PaperPlaneDeemo** [comment]
> wait what, how that can break compatibility.

The author privately replied to me, saying that CORS is used for WebDAV synchronization, and is meant to lift cross-origin restrictions, therefore it cannot be changed to 'edge'.

**Comment by H0llyW00dzZ** [comment]
Bruh,rip then runtime 'nodejs' cant do anything.
unlike runtime 'edge', example can build own browser in tauri app 🤣

**Pull request closed without merging**
