### PR TITLE
Fix Cloudflare Pages deployment issue and update related documents.

### PR DESCRIPTION
**Pull request by darth-pika-hu**
Fixed a issue which cause following error during Cloudflare Pages deployment:

The following routes were not configured to run with the Edge Runtime:
- /api/cors/[...path]

And Updated related documents.

### CODE REVIEW

**Comment by Yidadaa** [comment]
Vercel does not allow to use edge runtime to forward requests, which will break the /api/cors endpoint.

**Comment by darth-pika-hu** [comment]
So you mean Vercel will allow deployment with edge runtime but the function will break?On Nov 14, 2023, at 7:26 PM, Yifei Zhang ***@***.***> wrote:﻿
Vercel does not allow to use edge runtime to forward requests, which will break the /api/cors endpoint.

**Comment by H0llyW00dzZ** [comment]
its weird how vercel not allowing to use edge run time because of webdav syncing 
also about this a best UI / UX Project for AI it's recommended & better used to be in EDGE runtime instead of NodeJS runtime

**Comment by darth-pika-hu** [comment]
Is it because of Prisma? On Nov 15, 2023, at 3:08 AM, H0llyW00dzZ ***@***.***> wrote:﻿
its weird how vercel not allowing to use edge run time because of webdav syncing
also about this a best UI / UX Project for AI it's recommended & better used to be in EDGE runtime instead of NodeJS runtime

**Comment by H0llyW00dzZ** [comment]
> Is it because of Prisma? On Nov 15, 2023, at 3:08 AM, H0llyW00dzZ ***@***.***> wrote:﻿ its weird how vercel not allowing to use edge run time because of webdav syncing also about this a best UI / UX Project for AI it's recommended & better used to be in EDGE runtime instead of NodeJS runtime —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

read here https://github.com/Yidadaa/ChatGPT-Next-Web/pull/3182

**Pull request closed without merging**
