### PR TITLE
docker: Download prompts when build image

### PR DESCRIPTION
**Pull request by hibobmaster**
Using yarn install to prevent "error Your lockfile needs to be updated, but yarn was run with --frozen-lockfile"

### CODE REVIEW

**Comment by AprilNEA** [comment]
The lock file should be updated instead of modifying the Dockerfile

**Comment by hibobmaster** [comment]
Done!

**Comment by Yidadaa** [comment]
能否改成 yarn fetch，fetch 脚本之后可能会发生变动

**Comment by hibobmaster** [comment]
Done!

**Comment by Yidadaa** [comment]
`yarn build` 本身已经集成了拉取 prompts 的功能，目前 docker 构建存在的问题不是它导致的。

**Pull request closed without merging**
