### PR TITLE
remove redundant export

### PR DESCRIPTION
**Pull request by dvtate**

### CODE REVIEW

**Comment by dvtate** [comment]
why are all the messages being copied?

**Comment by H0llyW00dzZ** [comment]
@dvtate for filtering a messages response

**Comment by dvtate** [comment]
@H0llyW00dzZ  ok that makes sense we don't want to send the extra data in our request. Still the export at the end of the file is never used in the project and makes no sense as one should import it from elsewhere

**Comment by H0llyW00dzZ** [comment]
@dvtate might the owner forgot to removed it, or was used for some function before. (eg in old version)

**Comment by dvtate** [comment]
sure, either way, not needed anymore

**Comment by H0llyW00dzZ** [comment]
auto link pr : https://github.com/Yidadaa/ChatGPT-Next-Web/pull/1917
image

**Comment by dvtate** [comment]
that export never used

**Pull request closed without merging**
