### PR TITLE
Client App Always on top [Tauri]

### PR DESCRIPTION
**Pull request by H0llyW00dzZ**
Ref : [Feature] Client APP always on top #2997

[+] chore(tauri): update tauri features and configuration
- Update tauri features in Cargo.toml
- Add "setAlwaysOnTop" feature in tauri.conf.json

### CODE REVIEW

**Comment by Yidadaa** [comment]
We can simply add a pin icon here:

image

You can find the icon at /app/icons/pin.svg

**Comment by H0llyW00dzZ** [comment]
for tauri api set always on top ?

**Comment by Yidadaa** [comment]
Sure, user clicks the pin button, and it will call the tauri api to toggle `AlwaysOnTop` status.

**Comment by H0llyW00dzZ** [comment]
@Yidadaa test now

**Comment by H0llyW00dzZ** [comment]
may you can fix this for runtime nodejs
 ⚠ Using edge runtime on a page currently disables static generation for that page

> Build error occurred
Error: Page "/api/cors/[...path]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.

**Comment by H0llyW00dzZ** [comment]
@Yidadaa sorry this can't be done quickly

a doc in tauri its weird 
https://tauri.app/v1/api/js/window

this should be right

image

but when trying 
image

**Pull request closed without merging**
