### PR TITLE
[Fix] adjust presence_penalty step 0.1

### PR DESCRIPTION
**Pull request by 0x9be00ff1**

### CODE REVIEW

**Comment by Yidadaa** [comment]
搞这么精细干啥，这参数没什么用，太细的话不好操作

**Comment by 0x9be00ff1** [comment]
According to the document, 

https://platform.openai.com/docs/api-reference/parameter-details

> Reasonable values for the penalty coefficients are around 0.1 to 1 if the aim is to just reduce repetitive samples somewhat. 

0.1 appears to be a more reasonable option.

**Comment by Yidadaa** [comment]
does not mean step 0.1 is reasonable

**Comment by 0x9be00ff1** [comment]
can not set to min reasonable value 0.1

**Pull request merged**
