### PR TITLE
Add setting for HIDE_USER_API_KEY

### PR DESCRIPTION
**Pull request by KeithHello**
- change the wording of the Unauthorized situation based on the setting of HIDE_USER_API_KEY
  - Reason
    - No need to require a user API Key while the user API Key is forbidden

### CODE REVIEW

**Comment by H0llyW00dzZ** [comment]
Great, you add that in `build.ts`
about me I made this hahaha https://chatgpt.btz.sh/#/changelog

**Comment by H0llyW00dzZ** [comment]
btw I wanted request you to add this if you like it
`const isOpenaiApiKey = process.env.OPENAI_API_KEY !== undefined;`
and this for a return
`isOpenaiApiKey,`
so it will created `(property) isOpenaiApiKey: boolean` which is can be used as if `isOpenaiApiKey: false` (no environment variable openai apikey in .env) then in auth page only enter user own openai api key (no access code)

**Comment by KeithHello** [comment]
@H0llyW00dzZ 
Hello [H0llyW00dzZ](https://github.com/H0llyW00dzZ)

Sorry, I just noticed your reply in the morning, and thank you for your reply.

I added the logic for isSysHasOpenaiApiKey and changed your code a little bit,
Your code here is to find out whether the env variable is an empty string, but the value is actually undefined.
`const isSysHasOpenaiApiKey = process.env.OPENAI_API_KEY !== '';` → `const isSysHasOpenaiApiKey = !!process.env.OPENAI_API_KEY;`

chatgpt-next-web-logic-change

---
Here is the result of the code, I made some tests and it seems working well.
Please have a check.

chatgpt-next-web-openaikey

**Comment by H0llyW00dzZ** [comment]
check this one :
https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/commit/132a23cd1daea14b026a1cab63a9f894adef6d28
and this the ui page
- auth : 
https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/pull/52/commits/f54fe9e91fcd8cbf9585e0e50fb7e21e8cfe007d#diff-f5885e4b73a2e1c1cca6ec9d3217966f2ba723223219a1b3aa1239a6b1d2589b
- settings : 
https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/pull/52/commits/f54fe9e91fcd8cbf9585e0e50fb7e21e8cfe007d#diff-85f16a3c10276e127e4b2a0fe15953fa7be816d7bec3d87c90cd63f9b3cf1fbc

**Comment by H0llyW00dzZ** [comment]
should be work like this : 

image
image
in settings : 

image
there is no access code now since in env are empty for openai api key
image

when authorized (use own openai apikey) like in client app :

image

**Comment by KeithHello** [comment]
Thanks for your advice.

Please forgive me for confirming your request before changing the code.
In case I made some wrong coding.

---
## Request
- Change the **client app page** showing the access code and API key according to the settings of `isSysHasOpenaiApiKey` and `isHideUserApiKey`
  - Status: Done with current commits
- Change the **auth page** showing the access code and API key according to the settings of `isSysHasOpenaiApiKey` and `isHideUserApiKey`
  - Status: Not yet finished and expected to be modified

Is my understanding correct?

---
One more thing to notice, the code here may be not correct.
Because the value of process.env.OPENAI_API_KEY would be `undefined` rather than empty string '' when empty for openai api key

https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/commit/132a23cd1daea14b026a1cab63a9f894adef6d28

**Comment by H0llyW00dzZ** [comment]
in vercel as long like this it would be fine
image

**Comment by KeithHello** [comment]
@H0llyW00dzZ 
Understood, you are responding to my modification to the change of `const isSysHasOpenaiApiKey = process.env.OPENAI_API_KEY !== '';`

> before was process.env.OPENAI_API_KEY !== undefined; which if there is no OPENAI_API_KEY in env (this bad)

Yes, I agree with you.
I think it would be better to use `const isSysHasOpenaiApiKey = !!process.env.OPENAI_API_KEY`.

The value of  **process.env.OPENAI_API_KEY** is going to be `empty string` for vercel and `undefined` for local development. 
If it is coded as `process.env.OPENAI_API_KEY !== '';`, we may meet some difficulty in local development.
You can handle both `empty string` and `undefined` by this setting.

**Comment by H0llyW00dzZ** [comment]
oh wait really ? i don't know that can handle both

**Comment by H0llyW00dzZ** [comment]
@KeithHello btw thanks I added to my main forks

**Comment by KeithHello** [comment]
`!!process.env.OPENAI_API_KEY` means that we change the string value to boolean.
So both undefined and empty string are handled as `false` in boolean.

**Comment by H0llyW00dzZ** [comment]
thanks for the info
now its better

**Comment by KeithHello** [comment]
Btw how to handle this PR?
You can close this PR if you already have all the source change

**Comment by H0llyW00dzZ** [comment]
this pr into main @Yidadaa 
its only @Yidadaa

**Pull request closed without merging**
