### PR TITLE
fix cloudflare deployment instructions

### PR DESCRIPTION
**Pull request by rickyrobinett**
This update resolves an error when trying to deploy an error on cloudflare.

### CODE REVIEW

**Comment by rickyrobinett** [comment]
Thanks for accepting my PR @Yidadaa. Love the project. Ok if i remove deprecated from the Cloudflare docs section in the README? Now that this is working I'm willing to continue to ensure this doesn't break again

**Comment by ShinChven** [comment]
Still getting error:

```log


15:03:44.704 | ▲  Warning: Could not identify Next.js version, ensure it is defined as a project dependency.
-- | --
15:03:44.788 | ▲  Error: No Next.js version could be detected in your project. Make sure `"next"` is installed in "dependencies" or "devDependencies"
15:03:44.895 |  
15:03:44.895 | ⚡️ The Vercel build (`npx vercel build`) command failed. For more details see the Vercel logs above.
15:03:44.896 | ⚡️ If you need help solving the issue, refer to the Vercel or Next.js documentation or their repositories.
15:03:44.896 |  
15:03:44.923 | Failed: Error while executing user command. Exited with error code: 1
15:03:44.933 | Failed: build command exited with code: 1
15:03:45.894 | Failed: error occurred while running build command


```

**Comment by daiaji** [comment]
```
01:05:41.749 | ⚡️ Completed `yarn vercel build`.
-- | --
01:05:42.748 |  
01:05:42.748 | ⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
01:05:42.749 | ⚡️
01:05:42.749 | ⚡️ 	The following routes were not configured to run with the Edge Runtime:
01:05:42.749 | ⚡️ 	  - /api/cors/[...path]
01:05:42.749 | ⚡️
01:05:42.749 | ⚡️ 	Please make sure that all your non-static routes export the following edge runtime route segment config:
01:05:42.749 | ⚡️ 	  export const runtime = 'edge';
01:05:42.749 | ⚡️
01:05:42.750 | ⚡️ 	You can read more about the Edge Runtime on the Next.js documentation:
01:05:42.750 | ⚡️ 	  https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes
01:05:42.750 |  
01:05:42.789 | Failed: build command exited with code: 1
01:05:43.706 | Failed: error occurred while running build command
```
Deployment still failed.

**Comment by reeink** [comment]
my deployments failed since commit https://github.com/Yidadaa/ChatGPT-Next-Web/commit/ebcb2e7837e877fee5539b08a8e916fdce37086a . Same error with daiaji.

**Comment by 0xD8FF** [comment]
try changing the last line of app/api/cors/[...path]/route.ts to export const runtime = 'edge';

**Pull request merged**
