### PR TITLE
[Feature] Chats Export and Import as Backup

### PR DESCRIPTION
**Pull request by kfear1337**
[Feature] Chats Export and Import as Backup #2754
Screenshot : 
image

Logs Commit :
[[+] Export All data Include Settings](https://github.com/Yidadaa/ChatGPT-Next-Web/commit/0df4fa064dc7fcd94c9c3adc5745119f3661161f)
[[+] Import All data Include Settings](https://github.com/Yidadaa/ChatGPT-Next-Web/commit/c0e3100c178c3674974fcc9b0f394effd1f246c8)
[[+] Fixed Model in export and import](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2773/commits/eacca60849d03377c82dba33c9305a3845a18a9b)
[[+] Added global settings & Minor improvement](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2773/commits/3ea7c77f89c04dbdb838545c835b839586919454)
[[+] Added based of requested](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2773/commits/2f791efa9c150a06a9f7ca70198e80da621044cb)
[[+] Fix in config when import success it will reload](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2773/commits/8cd9b3baed01046dd3f6de040294cd21213c06fe)
[[+] Added Backup and Restore All Data](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2773/commits/b8bf2cae67b98676cd31592338063d23d6def516)
[[+] Fix language en and cn](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2773/commits/de9b6f380b5d9cc575a08052a4791ec684323605)

### CODE REVIEW

**Comment by Algorithm5838** [comment]
Great! I've just tried it, and it works exactly as intended.
I recommend considering the following reordering and renaming suggestions:
Screenshot 2023-09-07 at 09 11 03

**Comment by Algorithm5838** [comment]
I was thinking that perhaps we could replace the settings import and export feature with a backup button and a restore button. This way, users would be able to easily backup (Settings + Chats (including their settings) + Masks) and restore them. Considering that the number of individual settings is not significant, I don't believe it is necessary to have a separate backup option for settings alone.

**Comment by Yidadaa** [comment]
A more comprehensive idea is to merge all synchronization-related features together, including:
- Settings
- Chat
- Masks
- Prompts

Community users have always wanted the subscription feature for masks and prompts. In fact, it can be done together with the synchronization feature, merging them into a unified synchronization panel.

**Comment by kfear1337** [comment]
alright will working on it

**Comment by kfear1337** [comment]
@Yidadaa, @Algorithm5838 check latest commits I've been push

**Comment by Algorithm5838** [comment]
This is definitely better. However, my new preferred approach would be like this:
Screenshot 2023-09-07 at 16 03 35
Take notice of the new icon in the chat list. Clicking it will open a window that allows you to export or import all chats.

In terms of synchronization, I would prefer it to be a standalone feature. This way, I can have a local copy of my data without relying on a third party such as Google. Also, this would be useful when I want to just clear the browser's data or migrate to another browser.

**Comment by kfear1337** [comment]
still writing.. 
image
it will be better basically I made own for backup/restore because this one is not possible use default source from @Yidadaa so I have write it as own

**Comment by kfear1337** [comment]
@Algorithm5838 
btw what is this icon for ?
image

**Comment by Algorithm5838** [comment]
Import/Export of all chats. By clicking on it, a window will open, giving you the option to export or import all chats.
I repurposed it from Masks:
Screenshot 2023-09-07 at 16 41 37
Notice the two icons located in the upper-right corner.

**Comment by kfear1337** [comment]
oh that's ui
from now I'm gonna focusing it first to made possible about system for backup/restore
about ui later because its easy about ui
and can be customize by other developer

**Comment by kfear1337** [comment]
@Algorithm5838 check latest commits and try
screenshot : 
image

**Comment by Yidadaa** [comment]
I will do it in my way, sorry...

**Comment by kfear1337** [comment]
> **Note**
  >About `Backup/Restore All Data` It's Syncing the process of synchronizing all data, including messages, from the latest backup when they are exported into a `JSON` file. 
  >When restoring, it will retrieve data from the most recent backup created.
  >Support Restore All Platform or any browser
  >If you encounter any bugs, please let me know.

**Comment by kfear1337** [comment]
@Yidadaa it's fine
This repository has helped a lot of people from my country since I deployed it. That's why I started contributing. Initially, I was just looking around, but people from my country encouraged me to make my website featuring ChatGPT public.
and many people like it

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2796

**Pull request closed without merging**
