### PR TITLE
feat: add image viewer

### PR DESCRIPTION
**Pull request by TheRamU**
- Add image viewer
- Fixed thread blocking during image upload

### CODE REVIEW

**Comment by H0llyW00dzZ** [comment]
LGTM

**Comment by H0llyW00dzZ** [comment]
I cherry pick this pull requests, pretty useful

**Comment by H0llyW00dzZ** [comment]
@TheRamU  you may need fix this

image

image


image

**Comment by H0llyW00dzZ** [comment]
LGTM. 

now it should be fine from memory leaks especially on mobile

image

image

the only thing left now only fix this one later,

image

also that one it's not cause of image viewer

**Comment by H0llyW00dzZ** [comment]
Show off I am so cool


image

**Comment by H0llyW00dzZ** [comment]
anyway this stable and pretty useful, why not merge into the main then release lmao

**Comment by H0llyW00dzZ** [comment]
plus the function and ui can be reused for improve,etc

**Review by Marcos-Montero — APPROVED** [review]

**Pull request closed without merging**
